### PR TITLE
PuppetDB/Puppetboard: fix containers syntax and allow alternate containerPort

### PR DESCRIPTION
**Pull request by raphink**
The `indent` syntax actually doesn't work as expected with this chart, so this fixes it.

### CODE REVIEW

**Review by Xtigyro — APPROVED** [review]

**Review by Xtigyro — CHANGES_REQUESTED** [review]
Hey @raphink - the Changelog needs updating. Everything else is very nice!

**Comment by raphink** [comment]
Ah yes, the changelog. I see it has a `github-changelog-generator` footer, but the format is not of `github-changelog-generator`. Would you like to generate that changelog eventually?

**Comment by raphink** [comment]
Added manual CHANGELOG entry for now, and upgraded version to 5.5.0 because of recent enhancement.

**Review by Xtigyro — DISMISSED** [review]
LGTM 👍

**Review by Xtigyro — APPROVED** [review]
LGTM 👍

**Pull request merged**
