### PR TITLE
This line is not necessary, and it is causing puppetdb to crash.

### PR DESCRIPTION
**Pull request by felipeatsix**
As discussed on #202 I'm opening this PR with this simple fix.

### CODE REVIEW

**Comment by Xtigyro** [comment]
@felipeatsix Thanks for your contribution! 

You'd need to sign the CLA. Could you please do so?

**Comment by Xtigyro** [comment]
@felipeatsix Could you please sign the CLA?

**Comment by felipeatsix** [comment]
Hi @Xtigyro sorry for the delay, I just noticed that my first commit was submitted using my company username, which it does not have a github account, now I have submitted another commit with my correct username and we can see the CLA assistant is complaining about only 1 out of 2 committers have signed it. 

What is the recommended solution in this case?

**Comment by Xtigyro** [comment]
@felipeatsix The CLA is still not signed. It should be here: https://cla-assistant.io/puppetlabs/puppetserver-helm-chart?pullRequest=203

Also - could you please update the `CHANGELOG` and bump the minor (second digit) chart version in `Chart.yaml`?

**Comment by felipeatsix** [comment]
@Xtigyro The CLA is signed by my personal github account, which is the only one I can use to sign it, however, the problem here is that I sent the first commit using my company git user, which it does not have a github user account related to it, and I can't sign the CLA for that account because it is unexisting in github.

Hence, I prepared a new PR using only my personal account, where I also provided the required changelog updates.

#204

**Pull request closed without merging**
