### PR TITLE
Use official Puppetboard image, use port 9090, and allow extra PuppetDB containers.

### PR DESCRIPTION
**Pull request by raphink**

### CODE REVIEW

**Comment by Xtigyro** [comment]
Hey @raphink 👋
Thank you for your contribution - it's an honour and very appreciated! 💯

Could you please update the `CHANGELOG.md` and bump the chart version in `Chart.yaml`?
You might want to include your name in the [Credits](https://github.com/puppetlabs/puppetserver-helm-chart#credits)?

**Review by Xtigyro — CHANGES_REQUESTED** [review]
Hey @raphink 👋
Thank you for your contribution - it's an honour and very appreciated! 💯

Could you please update the `CHANGELOG.md` and bump the chart version in `Chart.yaml`?
You might want to include your name in the [Credits](https://github.com/puppetlabs/puppetserver-helm-chart#credits)?

**Comment by raphink** [comment]
No problem. I have several changes to make, so I was thinking of getting a few things merged before making a new release. Or do you really want to make one release per PR?

**Comment by Xtigyro** [comment]
@raphink Yeah - small steps without too much planning should work well enough. I think we all are busy people and that might make it a little bit easier for us. Also - it creates momentum and people might keep a closer look at the chart - which might help contributing to it further.

Also - I would be very happy if you can become an official maintainer (my birthday is in 3 days!)!

**Comment by raphink** [comment]
Would you like me to merge #85 into this PR then, to avoid two consecutive releases?

**Comment by Xtigyro** [comment]
Yes - sounds good! Thank you.

**Comment by raphink** [comment]
@Xtigyro I merged. I don't mind co-maintaining. I can't promise I'll have a lot of time, but at least now I have a project that uses this helm chart, so it makes sense 😁

**Comment by Xtigyro** [comment]
@raphink So how about putting this towards the top of the list and changing it to:

```
[Raphaël Pinson](https://github.com/raphink), Maintainer
```

Adding two lines here as well: https://github.com/puppetlabs/puppetserver-helm-chart/blob/master/Chart.yaml#L20

🙏

**Comment by raphink** [comment]
Done

**Comment by Xtigyro** [comment]
@raphink Thank you very much! 
P.S. I've added you to `CODEOWNERS` as well.

CC: @underscorgan @slconley @scottcressi

**Review by Xtigyro — APPROVED** [review]

**Pull request merged**
