### PR TITLE
delete parameter '--strip-components 1' Puppetserver certificate

### PR DESCRIPTION
**Pull request by orelops**

### CODE REVIEW

**Comment by Xtigyro** [comment]
> [CLA assistant check](https://cla-assistant.io/puppetlabs/puppetserver-helm-chart?pullRequest=106) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/puppetserver-helm-chart?pullRequest=106) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/puppetserver-helm-chart?pullRequest=106) it.

@orelops You will need to sign this (^_^).

**Review by Xtigyro — CHANGES_REQUESTED** [review]
Thanks for the contribution, @orelops! 🥇

Could you please update the `CHANGELOG.md` following the same pattern for previous releases and bump the minor chart version in `Chart.yaml`?

Ah, yeah - finally, you might want to include your name in the [Credits](https://github.com/puppetlabs/puppetserver-helm-chart#credits)? 🥇

**Comment by orelops** [comment]
@Xtigyro it is done ! thank you

**Review by Xtigyro — APPROVED** [review]
Thank you!

**Pull request merged**
