### PR TITLE
Save crl to defined filename

### PR DESCRIPTION
**Pull request by jfroche**
Do not assume the remote file name is `crl.pem`

### CODE REVIEW

**Comment by davidphay** [comment]
Thanks for the contribution @jfroche 

Could you please update the `CHANGELOG.md` and bump the minor chart version in `Chart.yaml` ?
You might want to include your name in the [Credits](https://github.com/puppetlabs/puppetserver-helm-chart#credits)?

**Comment by jfroche** [comment]
@davidphay sorry for the delay, I have updated the changelog & readme

**Review by Xtigyro — APPROVED** [review]
Thank you, @jfroche and @davidphay!

**Comment by Xtigyro** [comment]
Hey @davidphay - could you please check why GH Actions couldn't complete its run?

FYI: @jfroche @underscorgan

**Pull request merged**
