### PR TITLE
fixes #215 and allows customconfigs deployments in puppetdb

### LINKED ISSUE #215: Invalid Puppet DB Deployment
## Describe the Bug
This is invalid, you can't have 2 volumes with the same name. The Puppet DB deployment fails to deploy if custom config is used.

https://github.com/puppetlabs/puppetserver-helm-chart/blob/2665f8364b1bbf6d1a4b9b5ebbafc05207eff182/templates/puppetdb-deployment.yaml#L350-L359

## Expected Behavior
The item prefixed with the release name should remain, the other references an older config map name format which is not deployed in the current chart version. Removing the extra reference via a kustomize patch results in successful deployment.

## Steps to Reproduce
1. render chart with custom config defined via values for puppet db.
e.g. when using external DB
```
puppetdb:
  customconfigs:
    enabled: true
    configmaps:
      database.conf: |-
        database: {
          subname: "//"${PUPPETDB_POSTGRES_HOSTNAME}":"${PUPPETDB_POSTGRES_PORT}"/"${PUPPETDB_POSTGRES_DATABASE}
          username: puppetdb
          migrator-username: puppetdb
          connection-username: ${PUPPETDB_USER}
          connection-migrator-username: ${PUPPETDB_USER}
          password: ${PUPPETDB_PASSWORD}
          node-ttl: ${PUPPETDB_NODE_TTL}
          node-purge-ttl: ${PUPPETDB_NODE_PURGE_TTL}
          report-ttl: ${PUPPETDB_REPORT_TTL}
        }
```
3. attempt to deploy it
```
one or more objects failed to apply, reason: Deployment.apps "puppetserver-puppetdb" is invalid: spec.template.spec.volumes[2].name: Duplicate value: "puppetdb-custom-configs".
```
## Environment
All

### PR DESCRIPTION
**Pull request by anthonysomerset**
fixes #215 and allows customconfigs deployments in puppetdb by removing the duplicate volume mount block

### CODE REVIEW

**Comment by Xtigyro** [comment]
@anthonysomerset Would you mind please how your code is then sourced?

This one:

```yaml
puppetdb:
  tag: 7.18.0-v1.5.0
  extraEnv:
    PUPPETDB_POSTGRES_HOSTNAME: dbhostname.postgres.database.azure.com
  customconfigs:
    enabled: true
    configmaps:
      database.conf: |-
        database: {
          subname: "//"${PUPPETDB_POSTGRES_HOSTNAME}":"${PUPPETDB_POSTGRES_PORT}"/"${PUPPETDB_POSTGRES_DATABASE}
          username: ${PUPPETDB_USER}
          password: ${PUPPETDB_PASSWORD}
          node-ttl: ${PUPPETDB_NODE_TTL}
          node-purge-ttl: ${PUPPETDB_NODE_PURGE_TTL}
          report-ttl: ${PUPPETDB_REPORT_TTL}
          facts-blocklist: ".*veth.*"
          facts-blocklist-type: regex
        }
```

**Comment by anthonysomerset** [comment]
this is basically an example reference values.yaml that i used for testing and validation that the deployment works

the extraEnv for the db hostname was to respond to the referenced issue where the user needed to use an external DB and thus customconfigs is NOT required in their case anyway

the custom config was my example and use case of setting a facts-blocklist as a valid customconfig that did need such (and now works)

is that what you were looking for?

**Comment by Xtigyro** [comment]
@anthonysomerset Sorry, I am probably missing something but aren't you eliminating [here](https://github.com/puppetlabs/puppetserver-helm-chart/pull/227/files#diff-f816f97752a365403b980cb5d149805c65397aec8a70ff02d24d1a378058eafcL355-L359) the possibility the above to be sourced?

**Comment by anthonysomerset** [comment]
no - it now works without generating an error as in #215 

The configmap is an example to override database.conf, all but the last 2 lines are default config i am replaying for safety sake - might not be needed but haven't verified further either at this stage

**Review by Xtigyro — APPROVED** [review]

**Comment by Xtigyro** [comment]
@anthonysomerset Thank you!

I believe it would be very nice if you become part of the official maintainers - so please feel free to send a PR and add yourself. Should be [here](https://github.com/puppetlabs/puppetserver-helm-chart/blob/master/CODEOWNERS), [here](https://github.com/puppetlabs/puppetserver-helm-chart/blob/master/Chart.yaml#L18), and [here](https://github.com/puppetlabs/puppetserver-helm-chart/blob/master/README.md#credits). When we do that, I'll ask the `puppetlabs` GitHub owners to give you write access to this repo.

**Pull request merged**
