### PR TITLE
added extraContainers param to compilers and masters

### PR DESCRIPTION
**Pull request by skoef**
In my setup I need some additional sidecars to my compiler pods, this change allows for that!

### CODE REVIEW

**Review by Xtigyro — CHANGES_REQUESTED** [review]
Hey @skoef 👋
Thank you for your contribution once more - it's appreciated! 💯

Could you please update the CHANGELOG and bump the minor chart version in Chart.yaml?

**Comment by skoef** [comment]
Thanks for reviewing @Xtigyro! Perhaps if you agree with #122 as well, we can include them both in the same release, then I'll update the changelog and version in #122?

**Comment by Xtigyro** [comment]
> Thanks for reviewing @Xtigyro! Perhaps if you agree with #122 as well, we can include them both in the same release, then I'll update the changelog and version in #122?

Yeah - cool, that will work as well! Thanks!

**Comment by skoef** [comment]
@Xtigyro done, you can merge them both if you like!

**Review by Xtigyro — APPROVED** [review]
@skoef Thank you!

**Pull request merged**
