### PR TITLE
Update CHANGELOG.md for v5.1.0

### PR DESCRIPTION
**Pull request by Xtigyro**

### CODE REVIEW

**Comment by Xtigyro** [comment]
CC: @underscorgan @slconley @Iristyle @scottcressi @mwaggett @nwolfe @adrienthebo @dhollinger @binford2k @alannab

**Comment by mwaggett** [comment]
Hey @Xtigyro! We love that you’ve been contributing to Puppet repos, but many of the folks that you’ve been pinging are not directly involved with the work you’ve been doing. I’ve opened a PR to add a CODEOWNERS file, which will automatically ping the relevant folks for review, so you shouldn’t need to directly ping anyone anymore: https://github.com/puppetlabs/puppetserver-helm-chart/pull/77 Thanks for all your contributions!

**Comment by Xtigyro** [comment]
@mwaggett You're welcome! I'll appreciate if we can merge this one - so that the new version of the chart can be officially released - would pretty awesome!

**Comment by mwaggett** [comment]
@Xtigyro I don't actually have any context for this project, so I don't think I'm the right person to review/merge this.

**Comment by Xtigyro** [comment]
@mwaggett Everything else has been merged. This is just a leftover needed for the release notes.

**Review by MikaelSmith — APPROVED** [review]

**Comment by Xtigyro** [comment]
@MikaelSmith Thank you!

**Pull request merged**
