### PR TITLE
fix "Set the version" job

### PR DESCRIPTION
**Pull request by davidphay**

### CODE REVIEW

**Comment by davidphay** [comment]
@Xtigyro It should be good this time!

**Review by Xtigyro — APPROVED** [review]

**Comment by Xtigyro** [comment]
@davidphay Thank you!

**Comment by Xtigyro** [comment]
@davidphay Worked!

- https://github.com/puppetlabs/puppetserver-helm-chart/releases/tag/v6.2.0

**Comment by davidphay** [comment]
Finally ! 
You can close the issue https://github.com/puppetlabs/puppetserver-helm-chart/issues/119 !

**Pull request merged**
