### PR TITLE
Allow configuration of update strategy for deployments and statefulsets

### PR DESCRIPTION
**Pull request by aidandj**
I left the defaults the same, just made them configurable.

Let me know what I should do for versioning and changelog

### CODE REVIEW

**Review by abottchen — DISMISSED** [review]
LGTM

**Review by Xtigyro — CHANGES_REQUESTED** [review]
Thanks for the contribution, @artificial-aidan! 🥇

Could you please update the `CHANGELOG.md` following the same pattern for previous releases and bump the minor chart version in `Chart.yaml`?

**Comment by Xtigyro** [comment]
@artificial-aidan Also - please document the new configurable values in the `README.md`.

**Comment by Xtigyro** [comment]
Ah, yeah - finally, you might want to include your name in the [Credits](https://github.com/puppetlabs/puppetserver-helm-chart#credits)? 🥇

**Comment by aidandj** [comment]
Finished all of the above.

By the way, the reason for doing this was because statefulsets and deployments with PVC's can't be updated with a rolling update, there are volume mount conflicts.

I didn't want to change the default without asking, but now that I have you guys here I think anything that uses a `volumeClaimTemplate` needs to be a recreate update.

But that may not be a minor change.

**Review by Xtigyro — APPROVED** [review]

**Comment by Xtigyro** [comment]
@artificial-aidan Thank ya!
And feel free to open another PR about changing the default behaviour - we can discuss it there.

**Pull request merged**
