### PR TITLE
Puppet certs import options

### PR DESCRIPTION
**Pull request by anthonysomerset**
this potentially solves #223

### CODE REVIEW

**Comment by Xtigyro** [comment]
@anthonysomerset Thank you for the contribution!

Could you please bump the minor chart version in `Chart.yaml`, update `CHANGELOG.md`, and, finally, run: `helm unittest . -u`?

**Review by Xtigyro — CHANGES_REQUESTED** [review]
@anthonysomerset Thank you for the contribution!

Could you please bump the minor chart version in `Chart.yaml`, update `CHANGELOG.md`, and, finally, run: `helm unittest . -u`?

**Comment by anthonysomerset** [comment]
all done

**Comment by anthonysomerset** [comment]
FYI seems the changelog was not updated for 9.4.0 so i also added that based on the release headline in github

**Comment by Xtigyro** [comment]
@anthonysomerset Thank you!

Could you please fix this lint error:
- https://github.com/puppetlabs/puppetserver-helm-chart/actions/runs/8922233404/job/24512252087?pr=224#step:8:33

**Comment by anthonysomerset** [comment]
done

**Review by Xtigyro — APPROVED** [review]
@anthonysomerset Thank you!

**Pull request merged**
