### PR TITLE
improve & fix r10k issue

### PR DESCRIPTION
**Pull request by davidphay**
- Fix r10k issue with multi master (deploy r10k as a pod instead of sidecar)
- remove r10k from master & compiler
- Allow r10k cron jobs to be disabled
- Allow multi hieradata repos
- Share puppet code volume between master/compiler/r10k
- restart automatically pods if configmap or secret change

### CODE REVIEW

**Review by Xtigyro — CHANGES_REQUESTED** [review]
Thanks for the contribution, @davidphayanouvong! 🥇

Could you please update the `CHANGELOG.md` following the same pattern for previous releases and bump the `major` chart version in `Chart.yaml`?

❗Have you tested this with multiple Puppet Masters and Compilers? And more specifically - with multiple compilers running in different cloud availability zones?

**Comment by davidphay** [comment]
@Xtigyro Changelog & chart are updated.

Tested use case:
- single master
- multi master
- single master / single compiler
- single master / multi compilers
- multi master / multi compilers

Unfortunately, I can't test with different cloud availability zones because I use an On-premise solution.

**Comment by Xtigyro** [comment]
@davidphayanouvong Understood - I'll try to test it by the end of tomorrow. Thanks!

**Comment by Xtigyro** [comment]
@davidphayanouvong I hate to say this but it appears not much has changed. Tested in AWS.

```
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  4m57s (x2 over 5m2s)  default-scheduler  0/3 nodes are available: 2 node(s) didn't find available persistent volumes to bind, 2 node(s) had volume node affinity conflict.
  Warning  FailedScheduling  14s (x5 over 4m54s)   default-scheduler  0/3 nodes are available: 3 node(s) had volume node affinity conflict.
```

**Comment by Xtigyro** [comment]
@davidphayanouvong Some time ago putting R10K as part of the pod of the Puppet Masters and Compilers was actually a feature. It used to be something similar to what you did and it's a great job but the cloud providers have their limitations, regrettably. 

Maybe we can still keep some of the new features apart from?

```
    Fix r10k issue with multi master (deploy r10k as a pod instead of sidecar)
    remove r10k from master & compiler
    Share puppet code volume between master/compiler/r10k
```

**Comment by davidphay** [comment]
@Xtigyro maybe it's a stupid quesiton, but did you create the pvc before ?

from the `puppetserver-deployment-masters.yaml`:
```yaml
volumes:
        - name: puppet-code-storage
        {{- if .Values.puppetserver.masters.customPersistentVolumeClaim.code.enable }}
          {{- toYaml .Values.puppetserver.masters.customPersistentVolumeClaim.code.config | nindent 10 }}
        {{- else }}
          persistentVolumeClaim:
            claimName: puppet-code-claim
        {{- end }}
        - name: puppet-ca-storage
        {{- if .Values.puppetserver.masters.customPersistentVolumeClaim.ca.enable }}
          {{- toYaml .Values.puppetserver.masters.customPersistentVolumeClaim.ca.config | nindent 10 }}
        {{- else }}
          persistentVolumeClaim:
            claimName: puppet-ca-claim
        {{- end }}
        - name: puppet-puppet-storage
        {{- if .Values.puppetserver.masters.customPersistentVolumeClaim.puppet.enable }}
          {{- toYaml .Values.puppetserver.masters.customPersistentVolumeClaim.puppet.config | nindent 10 }}
        {{- else }}
          persistentVolumeClaim:
            claimName: puppet-puppet-claim
        {{- end }}
        - name: puppet-serverdata-storage
        {{- if .Values.puppetserver.masters.customPersistentVolumeClaim.serverdata.enable }}
          {{- toYaml .Values.puppetserver.masters.customPersistentVolumeClaim.serverdata.config | nindent 10 }}
        {{- else }}
          persistentVolumeClaim:
            claimName: puppet-serverdata-claim
        {{- end }}
```

**Comment by Xtigyro** [comment]
@davidphayanouvong You mean whether the chart was deployed before my test? If that's whatcha meant, then no - it was a completely new Amazon EKS cluster specifically created for testing your PR.

**Comment by Xtigyro** [comment]
@davidphayanouvong You can find me on `Puppet Community` Slack workspace - `Miro Hadzhiev` - and we can discuss it in more details. Or we can continue here, ofc.

**Comment by davidphay** [comment]
@Xtigyro I added you on slack

**Comment by davidphay** [comment]
New PR to implement only new feature: https://github.com/puppetlabs/puppetserver-helm-chart/pull/113

**Pull request closed without merging**
