### PR TITLE
Allow puppet compilers & r10k as deployment

### PR DESCRIPTION
**Pull request by davidphay**

### CODE REVIEW

**Comment by davidphay** [comment]
it allow to run compilers as deployment instead of statefulset (we can choose) et run r10k as  deployement instead of container sidecar.
The main interest is to share the `code` volume between all puppetservers (master or compilers depends on the setup)

**Review by Xtigyro — CHANGES_REQUESTED** [review]
Lovely work - thank you, @davidphay!

A question though - without changing any Helm values will an old Puppetserver Helm release still work? In other words - are there any breaking changes?

**Comment by davidphay** [comment]
I had a doubt, but just checked no :)

only the chart version of all resources but thats definitly normal

**Review by Xtigyro — APPROVED** [review]
Thank you!

**Pull request merged**
