### PR TITLE
Added the ability to use custom PVC 

### PR DESCRIPTION
**Pull request by HryhoriiDidenko**
To decouple the PVС configuration from the chart and be able to use custom PVС, I added these changes.

### CODE REVIEW

**Review by Xtigyro — CHANGES_REQUESTED** [review]
Hey @HryhoriiDidenko - this is super nice! Thank you for the contribution!

Do you mind bumping the version of the chart to `5.1.0` instead?

**Comment by Xtigyro** [comment]
Also - please add your name here (if you want to). 🥇 
-- https://github.com/puppetlabs/puppetserver-helm-chart#credits

**Comment by HryhoriiDidenko** [comment]
> Also - please add your name here (if you want to). 🥇
> -- https://github.com/puppetlabs/puppetserver-helm-chart#credits
@Xtigyro Thanks for your approve

**Comment by HryhoriiDidenko** [comment]
> Hey @HryhoriiDidenko - this is super nice! Thank you for the contribution!
> 
> Do you mind bumping the version of the chart to `5.1.0` instead?

I changed the version of the chart)

**Review by Xtigyro — APPROVED** [review]

**Pull request merged**
