### PR TITLE
various improvements so that foreman relevant configuration can be injected

### PR DESCRIPTION
**Pull request by simonfuhrer**
- feat: optional deployment of the puppetdb component (default true)
- feat: remove privileged from securityContext (I do not understand why it was used/needed??)
- feat: inject custom entrypoints which will be exuected during puppetserver startup
- feat: inject custom configmaps to configure puppetserver itself (configmaps mounted in /etc/puppetlabs/puppetserver/conf.d)
- feat: support extra r10k hiera & code repositories
- feat: add a restic backup Cronjob to backup our puppetserver master pv's
- fix: use r10k code & hiera extrasettings as map (global r10k configuration can be injected this way)
- fix: puppet service configured as ClusterIP only.
- fix: if compilers are deployed remove r10k container & code volumes from masters

### CODE REVIEW

**Review by Xtigyro — CHANGES_REQUESTED** [review]
Thanks for the contribution, @simonfuhrer! 🥇

Could you please update the `CHANGELOG.md` following the same pattern for previous releases and bump the minor chart version in `Chart.yaml`?

Ah, yeah - finally, you might want to include your name in the [Credits](https://github.com/puppetlabs/puppetserver-helm-chart#credits)? 🥇

**Comment by simonfuhrer** [comment]
@Xtigyro I updated the changelog and bumped the chart Version!

**Comment by simonfuhrer** [comment]
@Xtigyro in the meantime i've added another feature. would be great if you could review this too

thx

**Review by Xtigyro — APPROVED** [review]
Thank you, @simonfuhrer! That's a really nice PR, great work!

**Comment by Xtigyro** [comment]
@simonfuhrer Would you like to become one of the official maintainers of the chart?

**Comment by Xtigyro** [comment]
@simonfuhrer Would you like to become one of the maintainers of the chart?

**Pull request merged**
