### PR TITLE
feat(eyaml) Use secrets for eyaml keys

### PR DESCRIPTION
**Pull request by MeNsaaH**
I believe secrets such as eyaml keys should be stored as secrets and not as config maps. When using gitops tools e.g Argocd values for secrets are masked and configmaps are not.

### CODE REVIEW

**Review by Xtigyro — CHANGES_REQUESTED** [review]
Hey @MeNsaaH 👋
Thank you for your contribution - it's appreciated! 💯

Could you please update the `CHANGELOG` and bump the chart version in `Chart.yaml`?
You might want to include your name in the [Credits](https://github.com/puppetlabs/puppetserver-helm-chart#credits)?

**Comment by MeNsaaH** [comment]
@Xtigyro  I've done that.

**Comment by Xtigyro** [comment]
Hey @MeNsaaH - cool but could you please follow the pattern that we've followed so far re the `CHANGELOG`? I can see where you're going but we have some automated release process that relies on it.

**Comment by MeNsaaH** [comment]
Done @Xtigyro

**Review by Xtigyro — APPROVED** [review]

**Comment by Xtigyro** [comment]
Thank you, @MeNsaaH!

**Pull request merged**
