### PR TITLE
pgchecker doesn't work with external database

### PR DESCRIPTION
**Pull request by nielshojen**
Added the possibility of setting external postgresql.hostname with .Values.puppetdb.extraEnv.PUPPETDB_POSTGRES_HOSTNAME

### CODE REVIEW

**Comment by davidphay** [comment]
Hello, It's ok for me, just a minor issue on the changelog !

**Comment by JGodin-C2C** [comment]
Hello !

It seems that this PR can be merged ( and that would actually be really nice to have this feature ) 
Is it possible to go forward with this ?

**Comment by dabelenda** [comment]
@Xtigyro @davidphay any reason this PR is not approved?
This feature is really interesting for people who have a postgres setup with operational, HA and DR workflows already. Having a postgres deployed with a chart everywhere is a not great in that case.

**Comment by davidphay** [comment]
Hello, yes there is an issue with the changelog, I just wait this and I'll merge it afterward

@nielshojen can you fix the changelog please ?

**Comment by davidphay** [comment]
https://github.com/puppetlabs/puppetserver-helm-chart/pull/176

**Comment by nielshojen** [comment]
@davidphay Sorry I never got to finish this. I got involved in a car accident and have been out of it for a while. Good you got it sorted elsewhere

**Comment by JGodin-C2C** [comment]
OMG, I'm glad you Okay. 
Good to see you back. 
All the best. 

J\x00

**Pull request closed without merging**
