### PR TITLE
Add Single CA feature + fix minor issue

### PR DESCRIPTION
**Pull request by davidphay**
- feat: Single CA support (https://puppet.com/docs/puppet/7/config_ssl_external_ca.html)
- fix: define `podsecuritypolicy.apiVersion`
- fix copy issue with eyaml keys when use `existingSecret`
- fix puppetdb volume issue when use `customPersistentVolumeClaim`
- refactoring serviceAccount name

### CODE REVIEW

**Comment by davidphay** [comment]
@Xtigyro should I write how to configure puppetserver with a single CA in the readme ?

**Comment by Xtigyro** [comment]
> @Xtigyro should I write how to configure puppetserver with a single CA in the readme ?

@davidphay Yeah - but you can be brief, just the very basics.

Also - this looks like a big release. How about bumping the major version in `Chart.yaml` of the chart?

**Comment by Xtigyro** [comment]
@MikaelSmith @underscorgan 

Could you please make sure @davidphay has `write` permissions for this repo?

**Comment by davidphay** [comment]
@Xtigyro I just bump the minor version because it wasn't break anything, but yes why not for the major version!

**Comment by davidphay** [comment]
@Xtigyro Done !

**Review by Xtigyro — APPROVED** [review]
@davidphay Simply awesome, man! Thank you! 🌟 ⭐ 🌟

**Comment by Xtigyro** [comment]
@davidphay Could you please check why that is?
- https://github.com/puppetlabs/puppetserver-helm-chart/runs/6746643515?check_suite_focus=true

**Comment by Xtigyro** [comment]
I think the inability to publish the new version of the chart might be related to the `postgresql` Helm chart. In other words - I'm not sure it's directly related to this PR. Maybe we can try bumping its version to the last `10.16.*`? However, we'll need also to drop the support for Helm v2 in our chart and also bump https://github.com/puppetlabs/puppetserver-helm-chart/blob/master/Chart.yaml#L1 to `v2`.

**Comment by davidphay** [comment]
@Xtigyro you're right, they cleaned their chart versions and the dependency doesn't exist anymore  
https://github.com/bitnami/charts/issues/10539

I tried with version 10.16.* seems it works

**Comment by Xtigyro** [comment]
@davidphay Very nice! Thank you!

**Pull request merged**
