### PR TITLE
feat(eyaml): allow more than one pub/priv keypair in existing eyaml key map

### PR DESCRIPTION
**Pull request by raphink**
Signed-off-by: Raphaël Pinson <raphael.pinson@camptocamp.com>

### CODE REVIEW

**Review by Xtigyro — APPROVED** [review]

**Review by Xtigyro — CHANGES_REQUESTED** [review]
Hey @raphink - could you please bump the chart version and update the changelog?

**Comment by Xtigyro** [comment]
@raphink You would need to sign the CLA too. 👍

**Comment by raphink** [comment]
@Xtigyro done, sorry I forgot about that.

**Review by Xtigyro — APPROVED** [review]
@raphink Thank you!

**Pull request merged**
