### PR TITLE
added r10k.code.cronJob.successFile param

### PR DESCRIPTION
**Pull request by skoef**
In my setup I need the file reflecting whether the r10k code cronjob succeeded on a different volume, this change allows me to easily adjust this. Same thing goes for the hiera cronjob.

### CODE REVIEW

**Review by Xtigyro — CHANGES_REQUESTED** [review]
Hey @skoef 👋
Thank you for your contribution once more! 💯

Same thing - could you please update the CHANGELOG and bump the minor chart version in Chart.yaml? Please make sure to bump it `+1` than what you're gonna do in your other PR.

**Review by Xtigyro — APPROVED** [review]

**Comment by Xtigyro** [comment]
@skoef Wanna become an official maintainer of the chart?

**Comment by skoef** [comment]
@Xtigyro I would be honoured! ☺️

**Comment by Xtigyro** [comment]
> @Xtigyro I would be honoured! ☺️

@skoef Very nice! 🙇‍♂️ 

Please feel free to send a PR and bring your name towards the top in the `Credits` section and change the word `Contributor` to `Maintainer`. Also - add yourself to the `Chart.yaml`. And last but not least - please add your GH username to `CODEOWNERS`.

You can msg me in the Puppet Community Slack Workspace anytime - `Miro Hadzhiev`.

**Pull request merged**
